// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtOUk23PrTjn_CXbMf36CRcOK7LnHYGos',
    appId: '1:946063364931:web:b77a759b6b9df96757d5f6',
    messagingSenderId: '946063364931',
    projectId: 'yourappname-9aca3',
    authDomain: 'yourappname-9aca3.firebaseapp.com',
    storageBucket: 'yourappname-9aca3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORaonzstIpKxEcvdT14tr44nKnJzO0Co',
    appId: '1:946063364931:android:cd523b5793563a3257d5f6',
    messagingSenderId: '946063364931',
    projectId: 'yourappname-9aca3',
    storageBucket: 'yourappname-9aca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8lz2mfppOZhU4AH9F2pWx3Os6IcoACg',
    appId: '1:946063364931:ios:7b130569ab62d92257d5f6',
    messagingSenderId: '946063364931',
    projectId: 'yourappname-9aca3',
    storageBucket: 'yourappname-9aca3.appspot.com',
    androidClientId: '946063364931-on7ef7qpcps70n63fvv34krka4hsvsun.apps.googleusercontent.com',
    iosClientId: '946063364931-mf45cskfiqtc63namugb7n5usvgm8vkq.apps.googleusercontent.com',
    iosBundleId: 'com.jamia.deenulqayyim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8lz2mfppOZhU4AH9F2pWx3Os6IcoACg',
    appId: '1:946063364931:ios:7b130569ab62d92257d5f6',
    messagingSenderId: '946063364931',
    projectId: 'yourappname-9aca3',
    storageBucket: 'yourappname-9aca3.appspot.com',
    androidClientId: '946063364931-on7ef7qpcps70n63fvv34krka4hsvsun.apps.googleusercontent.com',
    iosClientId: '946063364931-mf45cskfiqtc63namugb7n5usvgm8vkq.apps.googleusercontent.com',
    iosBundleId: 'com.jamia.deenulqayyim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtOUk23PrTjn_CXbMf36CRcOK7LnHYGos',
    appId: '1:946063364931:web:b77a759b6b9df96757d5f6',
    messagingSenderId: '946063364931',
    projectId: 'yourappname-9aca3',
    authDomain: 'yourappname-9aca3.firebaseapp.com',
    storageBucket: 'yourappname-9aca3.appspot.com',
  );

}