name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.7.5
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  universal_html: ^2.2.4
  video_player: ^2.7.2
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
